### ISSUE TITLE
Request: Add GeoJsonPolygonStyle from android-map-utils

### ISSUE THREAD

**Issue by chitgoks** [SupasinTatiyanupanwong/map-kit-android-utils#2]
Possible? Your library is a must use for every developer integrating both hms and gms in 1 project

**Comment by SupasinTatiyanupanwong** [comment]
Hi,

It is available via `GeoJsonPolygon.Style `.

Yeah, when I started this, it is not 1:1 with the original API, but kinda close. I'm right now not sure if I made a good decision. 😅

**Comment by chitgoks** [comment]
Thanks! :D It may be better to follow the same class names so as not to confuse. but im not complaining  :D

**Comment by SupasinTatiyanupanwong** [comment]
Haha, I understand yours point, but the Map Kit itself is not really follow the same class names have in both Google Maps and Huawei Maps API, e.g. `MarkerOptions` -> `Marker.Options` so I was think it is better to have its name aligned with the same format  as in Map Kit lib.

I'll add migration guide in README like in Map Kit then.  😁

**Comment by chitgoks** [comment]
your instructions in the readme in mapkit were clear. its not a prob

the mapkit-android-utils did not specify anything about it. so i got lost
hahaha.

i have been waiting for google to provide a topojson layer. that ones gonna
be cool
